### ISSUE TITLE
sparsify_array(np.arange(10, dtype=np.int16), [True]).values returns inconsistent results

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [metagraph-dev/mlir-graphblas#167]
It's unclear if this is a bug or if this is just bad practice on my part. 

I expect this
```python3
    a = sparsify_array(np.arange(10, dtype=np.int16), [True])
    print(a.values)
```
to have the same results as this
```python3
    print(sparsify_array(np.arange(10, dtype=np.int16), [True]).values)
```

That's not the case as demonstrated by the script below.

<details>
  <summary>Click here to see the script.</summary>

  ```python
import numpy as np

from mlir_graphblas.tests.jit_engine_test_utils import sparsify_array

np.set_printoptions(linewidth=float('inf'))

print()

print("Expected:")
for _ in range(10):
    a = sparsify_array(np.arange(10, dtype=np.int16), [True])
    print(a.values)

print()

print("Unexpected:")
for _ in range(10):
    print(sparsify_array(np.arange(10, dtype=np.int16), [True]).values)

print()    

  ```
</details>

<details>
  <summary>Click here to see the script's result.</summary>

  ```

(mlirgraphblas) pnguyen@CONDA-0584:/$ python3 /tmp/script.py 

Expected:
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

Unexpected:
[  2311   1023   -251     -1 -23069   8877 -18466   5755   6192]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]
[    0     0     0 12288     0     0     0 12288     3]

(mlirgraphblas) pnguyen@CONDA-0584:/$ 
  ```
</details>

On the surface, it looks like the sparse array simply gets deallocated immediately before the access to the `values` attribute happens in `sparsify_array(np.arange(10, dtype=np.int16), [True]).values`. Not sure if this is a bug or just an expected sharp edge of using Python. 

CC @eriknw

**Comment by eriknw** [comment]
`.values` is a *view* of the underlying array.  So, I'm guessing the underlying array gets cleaned up.

There's a pretty loud warning about this here: https://numpy.org/doc/1.17/reference/c-api.array.html#c.PyArray_New

Assuming we want to avoid this vulnerability (and surprising behavior) while keeping the data as *views*, I think we probably need to set the base object of the array to the MLIRSparseTensor:

https://numpy.org/doc/1.17/reference/c-api.array.html#c.PyArray_SetBaseObject

Another option is to return a copy, but being able to assign into the underlying objects may be useful (is it?).
