### ISSUE TITLE
Replace "#SparseVec64" with "CV64"

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [metagraph-dev/mlir-graphblas#188]
In several places throughout our code base (e.g. in `tersify_mlir`) and documentation, we have two names for sparse vector encodings, `#SparseVec64` and `#CV64`.

```
#SparseVec64 = #sparse_tensor.encoding<{
  dimLevelType = [ "compressed" ],
  pointerBitWidth = 64,
  indexBitWidth = 64
}>
```

We should be consistent and pick one. I vote for `#CV64`.

**Comment by jim22k** [comment]
+1 for `#CV64`

**Comment by paul-tqh-nguyen** [comment]
https://github.com/metagraph-dev/mlir-graphblas/pull/191 replaces `#SparseVec64` with `#CV64`.
