### ISSUE TITLE
Duplicate passes in the explorer

### ISSUE THREAD

**Issue by seibert** [metagraph-dev/mlir-graphblas#21]
Although not common, sometimes we might want to run the same pass multiple times when compiling.  The duplicate named pass causes the explorer in the Sequential tab to get confused.  Example:
```
passes = [
    '--test-sparsification=lower=1',
    '--convert-linalg-to-loops',
    '--tensor-bufferize',
    '--func-bufferize',
    '--tensor-constant-bufferize',
    '--convert-linalg-to-loops',  # duplicate
    '--finalizing-bufferize',
    '--convert-scf-to-std',
    '--convert-std-to-llvm',
]
```

We should privately assign each stage a unique identifier in the explorer UI, even if the pass name is duplicated.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/metagraph-dev/mlir-graphblas/commit/97cff4a0ce906bdf8827950a98bbe1ac636409be Addresses this issue.
