### ISSUE TITLE
Argument to open explorer to specific page

### ISSUE THREAD

**Issue by seibert** [metagraph-dev/mlir-graphblas#31]
When making example notebooks, it would be handy to have optional arguments to the `explore()` method that would select the tab and pass to show initially.  This is helpful for demo notebooks where we might want to jump to a specific part of the translation process in an embedded explorer without having to tell the user where to click.

**Comment by jim22k** [comment]
This would be a useful feature to have

**Comment by seibert** [comment]
not sure if pygments is flexible enough, but also being able to pass line number ranges to make bold (or regular expressions?  I'm not sure what is easier...) would also help with tutorial materials.
