### ISSUE TITLE
Do not assume that getsitepackages() has a single entry in build.py

### ISSUE THREAD

**Issue by seibert** [metagraph-dev/mlir-graphblas#94]
From this issue:

https://github.com/metagraph-dev/mlir-graphblas/issues/90#issue-935014370

It seems that we are assuming that the return value of `site.getsitepackages()` will have only one element, but it can have multiple values.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/metagraph-dev/mlir-graphblas/pull/96 addresses this issue.
